[build]
  command = "pip install -r requirements.txt && python main.py"  # Build command to install dependencies and start the Flask application
  publish = "path/to/your/app"  # Specify the path to your Flask application

[dev]
  command = "python main.py"  # Command to run the Flask application locally in development

[[redirects]]
  from = "/*"
  to = "/main/:splat"
  status = 200
  force = true

[dev.environment]
  PORT = 5000  # Set the development port

[build.environment]
  PORT = 5000  # Set the production port
